import type { CockpitApi } from "../../engine/cockpit";
import type { ExposureApi } from "../../engine/exposure";
import type { IdentityApi } from "../../engine/identity";
import type { IncidentResponseApi } from "../../engine/incidentResponse";
import type { ResilienceApi } from "../../engine/resilience";
import type { RiskApi } from "../../engine/risk";
import type { SdlcApi } from "../../engine/sdlc";
import type { SecurityTestingApi } from "../../engine/securityTesting";
import type { VendorsApi } from "../../engine/vendors";
import type { VulnerabilitiesApi } from "../../engine/vulnerabilities";
import type { SystemRollup } from "../../engine/rollups";
import type { DataType } from "../../graph/nodes/dataTypes";
import type { ComplianceApi } from "../../engine/compliance";
import type { Responsibility } from "../../graph/edges/controlImplementations";

export type WorkspaceSystem = SystemRollup;
export type WorkspaceDataType = DataType;
export type CockpitSummary = ReturnType<CockpitApi["cockpitSummary"]>;
export type IdentityPosture = ReturnType<IdentityApi["identityPostureForSystem"]>;
export type ExposurePosture = ReturnType<ExposureApi["exposureForSystem"]>;
export type SecurityTestingPosture = ReturnType<SecurityTestingApi["securityTestsForSystem"]>;
export type ResiliencePosture = ReturnType<ResilienceApi["resilienceForSystem"]>;
export type IncidentResponsePosture = ReturnType<IncidentResponseApi["irForSystem"]>;
export type VendorPosture = ReturnType<VendorsApi["vendorsForSystem"]>;
export type VulnerabilityPosture = ReturnType<VulnerabilitiesApi["vulnerabilitiesForSystem"]>;
export type SdlcPosture = ReturnType<SdlcApi["sdlcForSystem"]>;
export type TopRisk = ReturnType<RiskApi["topRisksForSystem"]>[number];
export type ControlMatrixRow = ReturnType<ComplianceApi["systemControlMatrix"]>[number] & { responsibility: Responsibility };
export type ApplicabilitySummary = ReturnType<ComplianceApi["controlApplicabilitySummary"]>;
